class TryCatchProg1 {

	public static void main(String[] args) 
	{
		System.out.println(m1());
	}
	
	public static int m1()
	{
		int x=10;
		int y=1;
		int z=0;
		
		try {
			z=x/y;
		}
		System.out.println();
		catch(ArithmeticException ex)
		{
			System.out.println("exception handeled");
		}
		return z;
	}
